### ISSUE TITLE
chore: remove dependency on ipfs-unixfs

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia-unixfs#41]
https://github.com/ipfs/helia-unixfs/blob/933179c028805868dcf5bd0a936210eb6d653db9/packages/unixfs/src/commands/chmod.ts#LL6C25-L6C36

Or move that package from the [js-ipfs-unixfs](https://github.com/ipfs/js-ipfs-unixfs) repo: https://github.com/ipfs/js-ipfs-unixfs/tree/master/packages/ipfs-unixfs

or rename https://github.com/ipfs/js-ipfs-unixfs

related to https://github.com/ipfs/js-ipfs/issues/4336

**Comment by achingbrain** [comment]
What's the problem that this causes?
