### ISSUE TITLE
feat: No copy.

### ISSUE THREAD

**Issue by saul-jb** [ipfs/helia-unixfs#54]
It would be cool if this lib had a `nocopy` option like Kubo has. The no copy in Kubo uses the [filestore spec](https://gist.github.com/whyrusleeping/5565651011b49ddc9ddeec9ffd169050).

I believe this requires a special blockstore implementation, so I have made one here: https://github.com/ipfs/js-stores/pull/233

**Comment by achingbrain** [comment]
This can be implemented by a no-copy blockstore as you've found, so there's nothing to do here.

That said, the problem with `nocopy` is other processes changing the imported files behind the back of the blockstore which I don't think Kubo ever came up with a solution for.
