### ISSUE TITLE
onlyHash alternative?

### ISSUE THREAD

**Issue by buu700** [ipfs/helia-unixfs#58]
Is there an alternative to the [`onlyHash`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsadddata-options) option from ipfs-core? Nothing in the `ImporterOptions` interface looks similar.

I wasn't sure which repository was more appropriate, so I submitted the same issue here: https://github.com/ipfs/js-ipfs-unixfs/issues/342

**Comment by achingbrain** [comment]
You can create a unixfs instance that uses a [black hole blockstore](https://github.com/ipfs/js-stores/blob/main/packages/blockstore-core/src/black-hole.ts) - this will give you a hash without writing blocks anywhere.

```js
import { BlackHoleBlockstore } from 'blockstore-core/black-hole'
import { unixfs } from '@helia/unixfs'

const fs = unixfs({ blockstore: new BlackHoleBlockstore())
const cid = await fs.addFile(...)
```

**Comment by buu700** [comment]
That's perfect, thanks!
