### ISSUE TITLE
Unable to upload instance of File (Web API)

### ISSUE THREAD

**Issue by negamaxi** [ipfs/helia-unixfs#90]
This is the code:

![изображение](https://github.com/ipfs/helia-unixfs/assets/16529171/16352d28-0417-4ab7-b4e4-bc4d5f7e592f)

It tries to upload a bunch of files from a simple web form. But unix-fs throws error from this place:

![изображение](https://github.com/ipfs/helia-unixfs/assets/16529171/e02d0ae2-2edc-4c0e-9e62-4b0c3f15482d)

The same problem with `.addFile` unixfs API. It seems like helia unixfs doesn't support File (Blob) API as a file content.

**Comment by achingbrain** [comment]
You need to transform the Blob into one of the expected `content` types - `Uint8Array`, `AsyncIterable<Uint8Array>` or `Iterable<Uint8Array>`.

You can use [blob-to-it](https://www.npmjs.com/package/blob-to-it) to do this:

```js
import toIt from 'blob-to-it'

const addIterator = heliaFS.addAll(
  files.map(file => ({
    path: file.name,
    content: toIt(file)
  }), {
    wrapWithDirectory: true
  }
)
```

**Comment by negamaxi** [comment]
@achingbrain I've tried to use `file.stream()` [method](https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream) in place of a `file`. This method returns `ReadableStream` instance which [implements](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) async iterable protocol.

It works in Firefox and fails in Chrome because of the [issue](https://github.com/ipfs/js-ipfs-unixfs/issues/354) in js-ipfs-unixfs module.

Anyway will give your solution a try. Thanks.

**Comment by negamaxi** [comment]
Yep, `blob-to-it` made it work.
